/*
pub type Event<Type> = Option<Box<Type>>;
pub type Entity<Type> = Option<Box<Type>>;
*/

pub type Definition = Vec<Entity>;

#[derive( Clone, Debug )]
pub enum Entity<T=()>
{
    Defense,
    Offense,
    Perjorate,
    What,
    Who,
    Which,
    Where,
    Why,
    How,
    When,
    Mock,
    Inequal,
    Equal,
    Predicate,
    Compare,
    Indicate,
    Instance,
    Referral,
    Refer,
    Referrer,
    Reference,
    Transgender,
    Gender,
    Person,
    Animal,
    Animate,
    Inanimate,
    Project,
    Subject,
    Object,
    Place,
    Never,
    Sometime,
    Time,
    Abstract,
    Noun,
    Unknown,
    Is,
    Be,
    It,
    To,
    Use,
    Nor,
    Or,
    Inside,
    __(T)
}

#[derive( Clone, Debug )]
pub enum Identity
{
    Defense( Vec<Definition> ),
    Offense( Vec<Definition> ),
    Perjorate( Vec<Definition> ),
    What( Vec<Definition> ),
    Who( Vec<Definition> ),
    Which( Vec<Definition> ),
    Where( Vec<Definition> ),
    Why( Vec<Definition> ),
    How( Vec<Definition> ),
    When( Vec<Definition> ),
    Mock( Vec<Definition> ),
    Inequal( Vec<Definition> ),
    Equal( Vec<Definition> ),
    Predicate( Vec<Definition> ),
    Compare( Vec<Definition> ),
    Indicate( Vec<Definition> ),
    Instance( Vec<Definition> ),
    Referral( Vec<Definition> ),
    Refer( Vec<Definition> ),
    Referrer( Vec<Definition> ),
    Reference( Vec<Definition> ),
    Transgender( Vec<Definition> ),
    Gender( Vec<Definition> ),
    Person( Vec<Definition> ),
    Animal( Vec<Definition> ),
    Animate( Vec<Definition> ),
    Inanimate( Vec<Definition> ),
    Project( Vec<Definition> ),
    Subject( Vec<Definition> ),
    Object( Vec<Definition> ),
    Place( Vec<Definition> ),
    Never( Vec<Definition> ),
    Sometime( Vec<Definition> ),
    Time( Vec<Definition> ),
    Abstract( Vec<Definition> ),
    Noun( Vec<Definition> ),
    Unknown( Vec<Definition> ),
    Is( Vec<Definition> ),
    Be( Vec<Definition> ),
    It( Vec<Definition> ),
    To( Vec<Definition> ),
    Use( Vec<Definition> ),
    Nor( Vec<Definition> ),
    Or( Vec<Definition> ),
    __(),
}
